encyclopedia/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views
app='enc'
urlpatterns = [
    path('' , RedirectView.as_view(url='wiki/')),
    path("wiki/", views.index, name="index"),
    path ('wiki/<str:ent_name>',views.view_entry,name='entry'),
    path('newPage',views.new_page,name='new_page'),
    path('random',views.random_paging,name='rand'),
    path('searchResult',views.search_section,),
    path('edit/<str:entry>',views.edited)
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render,redirect
from markdown2 import markdown_path
from django.http import HttpResponse,Http404
import html
from . import util
import random
from django import forms
class edited_one(forms.Form):

    current=forms.CharField(label='page content md :',widget=forms.Textarea)
class new_one(forms.Form):
    title=forms.CharField(label='your title please  ',max_length=1000)
    markcontent=forms.CharField(label='\npage content as md  :',widget=forms.Textarea)
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
def view_entry(request,ent_name):
    try:
        a=markdown_path('entries/'+ent_name+'.md')
        a+="<p style='margin-top:50px;margin-left:4px;'><a href='/edit/{}' > Edit</a></p>".format(ent_name)
        return HttpResponse(a)
    except :
        return HttpResponse('sorry requested page not found')
def new_page(request):
    if request.method=='POST':
        a=util.list_entries()
        for i in range(len(a)):
            a[i]=a[i].lower()
        print(a)
        try:
            if request.POST.get('title').lower()  not in a:
                title=request.POST.get('title')
                content=request.POST.get('markcontent')
                file=open('entries/'+title+'.md','w')
                file.write(content)
                file.close()
                return redirect('wiki/'+title)
            else :
                return HttpResponse("""<h1>sorry it's already existed</h1><br>
                                    <br>
                                    <form action='wiki'>
                                    <input type='submit' value='back to main' style='margin-left:10%;'>
                                    </form>""")
        except:
            return HttpResponse('sorry try agian later')

    else :
        return render(request,'encyclopedia/create_entry.html',{'form':new_one})
def random_paging(request):
    pages=util.list_entries()
    hitted=random.choice(pages).lower()
    return redirect('wiki/'+hitted)
def search_section(request):
    entry=request.GET.get('q')
    print(entry.lower())
    entries=[i.lower() for i in util.list_entries()]
    print(entries)
    if entry.lower() in entries :
        return redirect('wiki/'+entry)
    else :
        result=[]
        for i in range(len(entries)):
            if entry.lower() in entries[i] :
                result.append(util.list_entries()[i])
        if len(result) != 0:
            return render(request,'encyclopedia/SearchReslut.html',{'suggestions':result})
        else :
            return HttpResponse("""<h1>sorry we didn't find existed results for your search</h1>
                                    <br>
                                    <br>
                                    <form action='wiki'>
                                    <input type='submit' value='back to main' style='margin-left:20%;'>
                                    </form>
                                    """)
def edited(request,entry):
    if request.method=='POST':
        new_entry=open('entries/'+entry+'.md','w')
        new_entry.write(request.POST.get("new_content"))
        new_entry.close()
        return redirect('/wiki/'+entry)
    else:
        old=open('entries/'+entry+'.md','r')
        current=old.read()
        old.close()
        print(current)
        return render(request,'encyclopedia/edit.html',{'content':current.strip(),'entry':entry})

encyclopedia/templates/encyclopedia/SearchReslut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search suggestions</title>
</head>
<body>
<P>your suggestions : </P>
<ol>
{% for i in suggestions %}
    <li> <a href="wiki/{{ i|lower }}"> {{ i }} </a> </li>
{% endfor %}
</ol>


</body>
</html>

encyclopedia/templates/encyclopedia/create_entry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}
{%  block title %}
    create page
{%  endblock %}
{% block body%}
    <form action='newPage' method="POST">
    {%  csrf_token %}
{{ form.title.label_tag }}  {{ form.title }}
        <br>
        {{ form.markcontent.label_tag}}
        <br>
        {{ form.markcontent }}
        <br>

       <!-- <label for="title">title :  </label>
        <input type="text" name="title" id="id_title"><br>
        -->
    <input type="submit" value="create" style="margin-left: 30%">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
<h1 id="title">{{ entry }} </h1>

<form action="/edit/{{entry}}" method="post">
    {% csrf_token %}
    <br>
    <br>
    <textarea name="new_content" style="width:50%;height:400px;margin-left: 20%">{{content}}
    </textarea>
    <br>
    <input type="submit" value="save" style="margin-left:45%;margin-top: 6px">
</form>
</body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }} ">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/searchResult" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'new_page' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{%  url 'rand' %}"> Random Page</a>
                </div>
                {% block nav %}

                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>